version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ${PROJECT_NAME}_web
    depends_on:
      - db
    env_file: .env
    environment:
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: password
      TZ: America/Los_Angeles
    image: ${PROJECT_NAME}:rubyland
    links:
      - db
    platform: linux/amd64
    ports:
      - "${HOST_PORT}:80"
    restart: unless-stopped
    volumes:
      - .:/app

  db:
    container_name: ${PROJECT_NAME}_db
    environment:
      POSTGRES_DB: ${PROJECT_NAME}_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    image: postgres:12.10
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
