version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ${APP_NAME}_web
    depends_on:
      - db
    env_file: .env
    environment:
      LOCAL: 'true'
      PASSENGER_APP_ENV: development
      TZ: America/Los_Angeles
    image: ${APP_NAME}:rubyland
    links:
      - db
    platform: linux/amd64
    ports:
      - "${HOST_APP_PORT}:80"
    restart: unless-stopped
    volumes:
      - .:/app

  db:
    container_name: ${APP_NAME}_db
    env_file: .env
    environment:
      POSTGRES_DB: ${APP_NAME}_development
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    image: postgres:12.10
    ports:
      - "${HOST_DB_PORT}:5432"
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
